apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
stringData:
  DB_USERNAME: laravel
  DB_PASSWORD: laravel
  APP_KEY: base64:kM1VXXlCkpzc7rtSsJX+YWcdf9oroik4TLPaQsN4+h4=
