apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ0b3JpY2VzcmFmYWVsIiwicGFzc3dvcmQiOiJkY2tyX3BhdF9NQmI5NkxwOGhDczRubXB2a0dtS3F5UDVZUTgiLCJlbWFpbCI6InRvcmljZXMucmFmYWVsQGdtYWlsLmNvbSIsImF1dGgiOiJkRzl5YVdObGMzSmhabUZsYkRwa1kydHlYM0JoZEY5TlFtSTVOa3h3T0doRGN6UnViWEIyYTBkdFMzRjVVRFZaVVRnPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2025-04-09T07:50:50Z"
  name: dockerhub-credentials
  namespace: argocd
  resourceVersion: "377628"
  uid: 7691ed35-76d8-417c-8776-50ca035d9905
type: kubernetes.io/dockerconfigjson
