# job to run php artisan migrate
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-job
spec:
  completions: 1
  template:
    metadata:
      name: mysql-job
    spec:
      restartPolicy: Never
      containers:
        - name: mysql-job
          image: toricesrafael/laravel-congress-app:9571bbf
          imagePullPolicy: Always
          command: ["php", "artisan", "migrate", "--force"]
          volumeMounts:
            - name: app-secret
              mountPath: /var/www/html/.env
              subPath: .env
      volumes:
        - name: app-secret
          secret:
            secretName: app-secret
