apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ewogICAgImtpbmQiOiAiU2VjcmV0IiwKICAgICJhcGlWZXJzaW9uIjogInYxIiwKICAgICJtZXRhZGF0YSI6IHsKICAgICAgICAibmFtZSI6ICJnaGNyLXNlY3JldCIsCiAgICAgICAgIm5hbWVzcGFjZSI6ICJkZWZhdWx0IiwKICAgICAgICAiY3JlYXRpb25UaW1lc3RhbXAiOiBudWxsCiAgICB9LAogICAgImRhdGEiOiB7CiAgICAgICAgIi5kb2NrZXJjb25maWdqc29uIjogImV5SmhkWFJvY3lJNmV5Sm5hR055TG1sdklqcDdJblZ6WlhKdVlXMWxJam9pVW1GbVlWUnZjbWxqWlhNaUxDSndZWE56ZDI5eVpDSTZJbWRvY0Y5alVGUjZUR2g0U0VWMFNsWXpZMUp0V1doRFZuWXpkVWc0Y1c1cFNWZ3hhRzh3Y2xVaUxDSmxiV0ZwYkNJNkluUnZjbWxqWlhNdWNtRm1ZV1ZzUUdkdFlXbHNMbU52YlNJc0ltRjFkR2dpT2lKVmJVWnRXVlpTZG1OdGJHcGFXRTAyV2pKb2QxZ3lUbEZXU0hCTllVaG9TVkpZVWt0V2FrNXFWVzB4V21GRlRsZGthazR4VTBSb2VHSnRiRXBYUkVadllucENlVlpSUFQwaWZYMTkiCiAgICB9LAogICAgInR5cGUiOiAia3ViZXJuZXRlcy5pby9kb2NrZXJjb25maWdqc29uIgp9Cg==
