apiVersion: batch/v1
kind: Job
metadata:
  name: app-job-migrate
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: app-job
          image: toricesrafael/laravel-congress-app:28a1369
          command: ["php", "artisan", "migrate", "--force"]
          env:
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: DB_CONNECTION
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: DB_HOST
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
      restartPolicy: Never
  backoffLimit: 3
