name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  Build-and-push:
    name: Build & Push Docker Image to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Generate image tag (commit SHA)
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/laravel-congress-app:${{ env.IMAGE_TAG }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/laravel-congress-app:${{ env.IMAGE_TAG }} \
                     ${{ secrets.DOCKERHUB_USERNAME }}/laravel-congress-app:latest
      
      - name: Push both tags
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/laravel-congress-app:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/laravel-congress-app:latest
      
      - name: Update Kubernetes deployment YAML
        run: |
            sed -i "s|\(image: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-congress-app:\).*|\1$IMAGE_TAG|" k8s/app/base/app/deployment.yaml
            sed -i "s|\(image: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-congress-app:\).*|\1$IMAGE_TAG|" k8s/app/base/job_argocd.yaml
            sed -i "s|\(image: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-congress-app:\).*|\1$IMAGE_TAG|" k8s/config/job.yaml
    
      - name: Commit and push updated manifest
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://${{ secrets.DOCKERHUB_TOKEN }}@github.com/${{ github.repository }}
          git add k8s/app/base/app/deployment.yaml
          git add k8s/app/base/job_argocd.yaml
          git add k8s/config/job.yaml
          git commit -m "Update image tag to $IMAGE_TAG"
          git push origin HEAD:main
      