name: Deploy to GHCR

on:
  push:
    branches:
      - main

jobs:
  Build-and-push:
    name: Build & Push Docker Image to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set lower-case repo name
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
        
      - name: Build Docker image
        run: |
            docker build -t ghcr.io/${REPO_LC}/laravel-congress-app:latest .
        
      - name: Push Docker image
        run: |
          docker push ghcr.io/${REPO_LC}/laravel-congress-app:latest
